name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish Blazor App
      run: dotnet publish -c Release -o release

    - name: Fix GitHub Pages settings
      run: |
        touch release/wwwroot/.nojekyll
        cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './release/wwwroot'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4